// Warning this file was generated by `gen.rb`

#[cfg(any(feature = "mysql", feature = "sqlite", feature = "postgres"))]
use sqlx::encode::Encode;
#[cfg(any(feature = "mysql", feature = "sqlite", feature = "postgres"))]
use sqlx::types::Type;

#[cfg(feature = "sqlite")]
use super::sqlite::SqliteParam;

#[cfg(feature = "sqlite-sync")]
use super::sqlite_sync::SqliteSyncParam;

#[cfg(feature = "mssql")]
use super::mssql::MssqlParam;

#[cfg(feature = "postgres")]
use super::postgres::PostgresParam;

#[cfg(feature = "mysql")]
use super::mysql::MysqlParam;

#[cfg(any(feature = "turso", feature = "turso-sync"))]
use super::turso::TursoParam;

#[cfg(all(feature = "sqlite-sync", not(feature = "turso-sync")))]
pub trait Param: SqliteSyncParam + rusqlite::types::ToSql {}

#[cfg(all(feature = "sqlite-sync", not(feature = "turso-sync")))]
impl<T> Param for T where T: rusqlite::types::FromSql + rusqlite::types::ToSql {}

#[cfg(all(feature = "turso-sync", not(feature = "sqlite-sync")))]
pub trait Param: TursoParam {}

#[cfg(all(feature = "turso-sync", not(feature = "sqlite-sync")))]
impl<T> Param for T where T: TursoParam {}

#[cfg(all(feature = "sqlite-sync", feature = "turso-sync"))]
pub trait Param: SqliteSyncParam + rusqlite::types::ToSql + TursoParam {}

#[cfg(all(feature = "sqlite-sync", feature = "turso-sync"))]
impl<T> Param for T where T: rusqlite::types::FromSql + rusqlite::types::ToSql + TursoParam {}

#[cfg(all(
    feature = "sqlite",
    not(feature = "postgres"),
    not(feature = "mysql"),
    not(feature = "mssql"),
    not(feature = "turso")
))]
pub trait Param: SqliteParam {}

#[cfg(all(
    feature = "sqlite",
    not(feature = "postgres"),
    not(feature = "mysql"),
    not(feature = "mssql"),
    not(feature = "turso")
))]
impl<T> Param for T
where
    for<'a> T: 'a + Send + Encode<'a, sqlx::Sqlite> + Type<sqlx::Sqlite>,
    for<'a> &'a T: Send,
{
}

#[cfg(all(
    feature = "postgres",
    not(feature = "sqlite"),
    not(feature = "mysql"),
    not(feature = "mssql"),
    not(feature = "turso")
))]
pub trait Param: PostgresParam {}

#[cfg(all(
    feature = "postgres",
    not(feature = "sqlite"),
    not(feature = "mysql"),
    not(feature = "mssql"),
    not(feature = "turso")
))]
impl<T> Param for T
where
    for<'a> T: 'a + Send + Encode<'a, sqlx::Postgres> + Type<sqlx::Postgres>,
    for<'a> &'a T: Send,
{
}

#[cfg(all(
    feature = "mysql",
    not(feature = "sqlite"),
    not(feature = "postgres"),
    not(feature = "mssql"),
    not(feature = "turso")
))]
pub trait Param: MysqlParam {}

#[cfg(all(
    feature = "mysql",
    not(feature = "sqlite"),
    not(feature = "postgres"),
    not(feature = "mssql"),
    not(feature = "turso")
))]
impl<T> Param for T
where
    for<'a> T: 'a + Send + Encode<'a, sqlx::MySql> + Type<sqlx::MySql>,
    for<'a> &'a T: Send,
{
}

#[cfg(all(
    feature = "mssql",
    not(feature = "sqlite"),
    not(feature = "postgres"),
    not(feature = "mysql"),
    not(feature = "turso")
))]
pub trait Param: MssqlParam {}

#[cfg(all(
    feature = "mssql",
    not(feature = "sqlite"),
    not(feature = "postgres"),
    not(feature = "mysql"),
    not(feature = "turso")
))]
impl<T> Param for T
where
    T: MssqlParam,
    for<'a> &'a T: Send,
{
}

#[cfg(all(
    feature = "turso",
    not(feature = "sqlite"),
    not(feature = "postgres"),
    not(feature = "mysql"),
    not(feature = "mssql")
))]
pub trait Param: TursoParam {}

#[cfg(all(
    feature = "turso",
    not(feature = "sqlite"),
    not(feature = "postgres"),
    not(feature = "mysql"),
    not(feature = "mssql")
))]
impl<T> Param for T
where
    T: TursoParam,
    for<'a> &'a T: Send,
{
}

#[cfg(all(
    feature = "sqlite",
    feature = "postgres",
    not(feature = "mysql"),
    not(feature = "mssql"),
    not(feature = "turso")
))]
pub trait Param: SqliteParam + PostgresParam {}

#[cfg(all(
    feature = "sqlite",
    feature = "postgres",
    not(feature = "mysql"),
    not(feature = "mssql"),
    not(feature = "turso")
))]
impl<T> Param for T
where
    for<'a> T: 'a
        + Send
        + Encode<'a, sqlx::Sqlite>
        + Type<sqlx::Sqlite>
        + Encode<'a, sqlx::Postgres>
        + Type<sqlx::Postgres>,
    for<'a> &'a T: Send,
{
}

#[cfg(all(
    feature = "sqlite",
    feature = "mysql",
    not(feature = "postgres"),
    not(feature = "mssql"),
    not(feature = "turso")
))]
pub trait Param: SqliteParam + MysqlParam {}

#[cfg(all(
    feature = "sqlite",
    feature = "mysql",
    not(feature = "postgres"),
    not(feature = "mssql"),
    not(feature = "turso")
))]
impl<T> Param for T
where
    for<'a> T: 'a
        + Send
        + Encode<'a, sqlx::Sqlite>
        + Type<sqlx::Sqlite>
        + Encode<'a, sqlx::MySql>
        + Type<sqlx::MySql>,
    for<'a> &'a T: Send,
{
}

#[cfg(all(
    feature = "sqlite",
    feature = "mssql",
    not(feature = "postgres"),
    not(feature = "mysql"),
    not(feature = "turso")
))]
pub trait Param: SqliteParam + MssqlParam {}

#[cfg(all(
    feature = "sqlite",
    feature = "mssql",
    not(feature = "postgres"),
    not(feature = "mysql"),
    not(feature = "turso")
))]
impl<T> Param for T
where
    for<'a> T: 'a + Send + Encode<'a, sqlx::Sqlite> + Type<sqlx::Sqlite> + MssqlParam,
    for<'a> &'a T: Send,
{
}

#[cfg(all(
    feature = "sqlite",
    feature = "turso",
    not(feature = "postgres"),
    not(feature = "mysql"),
    not(feature = "mssql")
))]
pub trait Param: SqliteParam + TursoParam {}

#[cfg(all(
    feature = "sqlite",
    feature = "turso",
    not(feature = "postgres"),
    not(feature = "mysql"),
    not(feature = "mssql")
))]
impl<T> Param for T
where
    for<'a> T: 'a + Send + Encode<'a, sqlx::Sqlite> + Type<sqlx::Sqlite> + TursoParam,
    for<'a> &'a T: Send,
{
}

#[cfg(all(
    feature = "postgres",
    feature = "mysql",
    not(feature = "sqlite"),
    not(feature = "mssql"),
    not(feature = "turso")
))]
pub trait Param: PostgresParam + MysqlParam {}

#[cfg(all(
    feature = "postgres",
    feature = "mysql",
    not(feature = "sqlite"),
    not(feature = "mssql"),
    not(feature = "turso")
))]
impl<T> Param for T
where
    for<'a> T: 'a
        + Send
        + Encode<'a, sqlx::Postgres>
        + Type<sqlx::Postgres>
        + Encode<'a, sqlx::MySql>
        + Type<sqlx::MySql>,
    for<'a> &'a T: Send,
{
}

#[cfg(all(
    feature = "postgres",
    feature = "mssql",
    not(feature = "sqlite"),
    not(feature = "mysql"),
    not(feature = "turso")
))]
pub trait Param: PostgresParam + MssqlParam {}

#[cfg(all(
    feature = "postgres",
    feature = "mssql",
    not(feature = "sqlite"),
    not(feature = "mysql"),
    not(feature = "turso")
))]
impl<T> Param for T
where
    for<'a> T: 'a + Send + Encode<'a, sqlx::Postgres> + Type<sqlx::Postgres> + MssqlParam,
    for<'a> &'a T: Send,
{
}

#[cfg(all(
    feature = "postgres",
    feature = "turso",
    not(feature = "sqlite"),
    not(feature = "mysql"),
    not(feature = "mssql")
))]
pub trait Param: PostgresParam + TursoParam {}

#[cfg(all(
    feature = "postgres",
    feature = "turso",
    not(feature = "sqlite"),
    not(feature = "mysql"),
    not(feature = "mssql")
))]
impl<T> Param for T
where
    for<'a> T: 'a + Send + Encode<'a, sqlx::Postgres> + Type<sqlx::Postgres> + TursoParam,
    for<'a> &'a T: Send,
{
}

#[cfg(all(
    feature = "mysql",
    feature = "mssql",
    not(feature = "sqlite"),
    not(feature = "postgres"),
    not(feature = "turso")
))]
pub trait Param: MysqlParam + MssqlParam {}

#[cfg(all(
    feature = "mysql",
    feature = "mssql",
    not(feature = "sqlite"),
    not(feature = "postgres"),
    not(feature = "turso")
))]
impl<T> Param for T
where
    for<'a> T: 'a + Send + Encode<'a, sqlx::MySql> + Type<sqlx::MySql> + MssqlParam,
    for<'a> &'a T: Send,
{
}

#[cfg(all(
    feature = "mysql",
    feature = "turso",
    not(feature = "sqlite"),
    not(feature = "postgres"),
    not(feature = "mssql")
))]
pub trait Param: MysqlParam + TursoParam {}

#[cfg(all(
    feature = "mysql",
    feature = "turso",
    not(feature = "sqlite"),
    not(feature = "postgres"),
    not(feature = "mssql")
))]
impl<T> Param for T
where
    for<'a> T: 'a + Send + Encode<'a, sqlx::MySql> + Type<sqlx::MySql> + TursoParam,
    for<'a> &'a T: Send,
{
}

#[cfg(all(
    feature = "mssql",
    feature = "turso",
    not(feature = "sqlite"),
    not(feature = "postgres"),
    not(feature = "mysql")
))]
pub trait Param: MssqlParam + TursoParam {}

#[cfg(all(
    feature = "mssql",
    feature = "turso",
    not(feature = "sqlite"),
    not(feature = "postgres"),
    not(feature = "mysql")
))]
impl<T> Param for T
where
    T: MssqlParam + TursoParam,
    for<'a> &'a T: Send,
{
}

#[cfg(all(
    feature = "sqlite",
    feature = "postgres",
    feature = "mysql",
    not(feature = "mssql"),
    not(feature = "turso")
))]
pub trait Param: SqliteParam + PostgresParam + MysqlParam {}

#[cfg(all(
    feature = "sqlite",
    feature = "postgres",
    feature = "mysql",
    not(feature = "mssql"),
    not(feature = "turso")
))]
impl<T> Param for T
where
    for<'a> T: 'a
        + Send
        + Encode<'a, sqlx::Sqlite>
        + Type<sqlx::Sqlite>
        + Encode<'a, sqlx::Postgres>
        + Type<sqlx::Postgres>
        + Encode<'a, sqlx::MySql>
        + Type<sqlx::MySql>,
    for<'a> &'a T: Send,
{
}

#[cfg(all(
    feature = "sqlite",
    feature = "postgres",
    feature = "mssql",
    not(feature = "mysql"),
    not(feature = "turso")
))]
pub trait Param: SqliteParam + PostgresParam + MssqlParam {}

#[cfg(all(
    feature = "sqlite",
    feature = "postgres",
    feature = "mssql",
    not(feature = "mysql"),
    not(feature = "turso")
))]
impl<T> Param for T
where
    for<'a> T: 'a
        + Send
        + Encode<'a, sqlx::Sqlite>
        + Type<sqlx::Sqlite>
        + Encode<'a, sqlx::Postgres>
        + Type<sqlx::Postgres>
        + MssqlParam,
    for<'a> &'a T: Send,
{
}

#[cfg(all(
    feature = "sqlite",
    feature = "postgres",
    feature = "turso",
    not(feature = "mysql"),
    not(feature = "mssql")
))]
pub trait Param: SqliteParam + PostgresParam + TursoParam {}

#[cfg(all(
    feature = "sqlite",
    feature = "postgres",
    feature = "turso",
    not(feature = "mysql"),
    not(feature = "mssql")
))]
impl<T> Param for T
where
    for<'a> T: 'a
        + Send
        + Encode<'a, sqlx::Sqlite>
        + Type<sqlx::Sqlite>
        + Encode<'a, sqlx::Postgres>
        + Type<sqlx::Postgres>
        + TursoParam,
    for<'a> &'a T: Send,
{
}

#[cfg(all(
    feature = "sqlite",
    feature = "mysql",
    feature = "mssql",
    not(feature = "postgres"),
    not(feature = "turso")
))]
pub trait Param: SqliteParam + MysqlParam + MssqlParam {}

#[cfg(all(
    feature = "sqlite",
    feature = "mysql",
    feature = "mssql",
    not(feature = "postgres"),
    not(feature = "turso")
))]
impl<T> Param for T
where
    for<'a> T: 'a
        + Send
        + Encode<'a, sqlx::Sqlite>
        + Type<sqlx::Sqlite>
        + Encode<'a, sqlx::MySql>
        + Type<sqlx::MySql>
        + MssqlParam,
    for<'a> &'a T: Send,
{
}

#[cfg(all(
    feature = "sqlite",
    feature = "mysql",
    feature = "turso",
    not(feature = "postgres"),
    not(feature = "mssql")
))]
pub trait Param: SqliteParam + MysqlParam + TursoParam {}

#[cfg(all(
    feature = "sqlite",
    feature = "mysql",
    feature = "turso",
    not(feature = "postgres"),
    not(feature = "mssql")
))]
impl<T> Param for T
where
    for<'a> T: 'a
        + Send
        + Encode<'a, sqlx::Sqlite>
        + Type<sqlx::Sqlite>
        + Encode<'a, sqlx::MySql>
        + Type<sqlx::MySql>
        + TursoParam,
    for<'a> &'a T: Send,
{
}

#[cfg(all(
    feature = "sqlite",
    feature = "mssql",
    feature = "turso",
    not(feature = "postgres"),
    not(feature = "mysql")
))]
pub trait Param: SqliteParam + MssqlParam + TursoParam {}

#[cfg(all(
    feature = "sqlite",
    feature = "mssql",
    feature = "turso",
    not(feature = "postgres"),
    not(feature = "mysql")
))]
impl<T> Param for T
where
    for<'a> T: 'a + Send + Encode<'a, sqlx::Sqlite> + Type<sqlx::Sqlite> + MssqlParam + TursoParam,
    for<'a> &'a T: Send,
{
}

#[cfg(all(
    feature = "postgres",
    feature = "mysql",
    feature = "mssql",
    not(feature = "sqlite"),
    not(feature = "turso")
))]
pub trait Param: PostgresParam + MysqlParam + MssqlParam {}

#[cfg(all(
    feature = "postgres",
    feature = "mysql",
    feature = "mssql",
    not(feature = "sqlite"),
    not(feature = "turso")
))]
impl<T> Param for T
where
    for<'a> T: 'a
        + Send
        + Encode<'a, sqlx::Postgres>
        + Type<sqlx::Postgres>
        + Encode<'a, sqlx::MySql>
        + Type<sqlx::MySql>
        + MssqlParam,
    for<'a> &'a T: Send,
{
}

#[cfg(all(
    feature = "postgres",
    feature = "mysql",
    feature = "turso",
    not(feature = "sqlite"),
    not(feature = "mssql")
))]
pub trait Param: PostgresParam + MysqlParam + TursoParam {}

#[cfg(all(
    feature = "postgres",
    feature = "mysql",
    feature = "turso",
    not(feature = "sqlite"),
    not(feature = "mssql")
))]
impl<T> Param for T
where
    for<'a> T: 'a
        + Send
        + Encode<'a, sqlx::Postgres>
        + Type<sqlx::Postgres>
        + Encode<'a, sqlx::MySql>
        + Type<sqlx::MySql>
        + TursoParam,
    for<'a> &'a T: Send,
{
}

#[cfg(all(
    feature = "postgres",
    feature = "mssql",
    feature = "turso",
    not(feature = "sqlite"),
    not(feature = "mysql")
))]
pub trait Param: PostgresParam + MssqlParam + TursoParam {}

#[cfg(all(
    feature = "postgres",
    feature = "mssql",
    feature = "turso",
    not(feature = "sqlite"),
    not(feature = "mysql")
))]
impl<T> Param for T
where
    for<'a> T:
        'a + Send + Encode<'a, sqlx::Postgres> + Type<sqlx::Postgres> + MssqlParam + TursoParam,
    for<'a> &'a T: Send,
{
}

#[cfg(all(
    feature = "mysql",
    feature = "mssql",
    feature = "turso",
    not(feature = "sqlite"),
    not(feature = "postgres")
))]
pub trait Param: MysqlParam + MssqlParam + TursoParam {}

#[cfg(all(
    feature = "mysql",
    feature = "mssql",
    feature = "turso",
    not(feature = "sqlite"),
    not(feature = "postgres")
))]
impl<T> Param for T
where
    for<'a> T: 'a + Send + Encode<'a, sqlx::MySql> + Type<sqlx::MySql> + MssqlParam + TursoParam,
    for<'a> &'a T: Send,
{
}

#[cfg(all(
    feature = "sqlite",
    feature = "postgres",
    feature = "mysql",
    feature = "mssql",
    not(feature = "turso")
))]
pub trait Param: SqliteParam + PostgresParam + MysqlParam + MssqlParam {}

#[cfg(all(
    feature = "sqlite",
    feature = "postgres",
    feature = "mysql",
    feature = "mssql",
    not(feature = "turso")
))]
impl<T> Param for T
where
    for<'a> T: 'a
        + Send
        + Encode<'a, sqlx::Sqlite>
        + Type<sqlx::Sqlite>
        + Encode<'a, sqlx::Postgres>
        + Type<sqlx::Postgres>
        + Encode<'a, sqlx::MySql>
        + Type<sqlx::MySql>
        + MssqlParam,
    for<'a> &'a T: Send,
{
}

#[cfg(all(
    feature = "sqlite",
    feature = "postgres",
    feature = "mysql",
    feature = "turso",
    not(feature = "mssql")
))]
pub trait Param: SqliteParam + PostgresParam + MysqlParam + TursoParam {}

#[cfg(all(
    feature = "sqlite",
    feature = "postgres",
    feature = "mysql",
    feature = "turso",
    not(feature = "mssql")
))]
impl<T> Param for T
where
    for<'a> T: 'a
        + Send
        + Encode<'a, sqlx::Sqlite>
        + Type<sqlx::Sqlite>
        + Encode<'a, sqlx::Postgres>
        + Type<sqlx::Postgres>
        + Encode<'a, sqlx::MySql>
        + Type<sqlx::MySql>
        + TursoParam,
    for<'a> &'a T: Send,
{
}

#[cfg(all(
    feature = "sqlite",
    feature = "postgres",
    feature = "mssql",
    feature = "turso",
    not(feature = "mysql")
))]
pub trait Param: SqliteParam + PostgresParam + MssqlParam + TursoParam {}

#[cfg(all(
    feature = "sqlite",
    feature = "postgres",
    feature = "mssql",
    feature = "turso",
    not(feature = "mysql")
))]
impl<T> Param for T
where
    for<'a> T: 'a
        + Send
        + Encode<'a, sqlx::Sqlite>
        + Type<sqlx::Sqlite>
        + Encode<'a, sqlx::Postgres>
        + Type<sqlx::Postgres>
        + MssqlParam
        + TursoParam,
    for<'a> &'a T: Send,
{
}

#[cfg(all(
    feature = "sqlite",
    feature = "mysql",
    feature = "mssql",
    feature = "turso",
    not(feature = "postgres")
))]
pub trait Param: SqliteParam + MysqlParam + MssqlParam + TursoParam {}

#[cfg(all(
    feature = "sqlite",
    feature = "mysql",
    feature = "mssql",
    feature = "turso",
    not(feature = "postgres")
))]
impl<T> Param for T
where
    for<'a> T: 'a
        + Send
        + Encode<'a, sqlx::Sqlite>
        + Type<sqlx::Sqlite>
        + Encode<'a, sqlx::MySql>
        + Type<sqlx::MySql>
        + MssqlParam
        + TursoParam,
    for<'a> &'a T: Send,
{
}

#[cfg(all(
    feature = "postgres",
    feature = "mysql",
    feature = "mssql",
    feature = "turso",
    not(feature = "sqlite")
))]
pub trait Param: PostgresParam + MysqlParam + MssqlParam + TursoParam {}

#[cfg(all(
    feature = "postgres",
    feature = "mysql",
    feature = "mssql",
    feature = "turso",
    not(feature = "sqlite")
))]
impl<T> Param for T
where
    for<'a> T: 'a
        + Send
        + Encode<'a, sqlx::Postgres>
        + Type<sqlx::Postgres>
        + Encode<'a, sqlx::MySql>
        + Type<sqlx::MySql>
        + MssqlParam
        + TursoParam,
    for<'a> &'a T: Send,
{
}

#[cfg(all(
    feature = "sqlite",
    feature = "postgres",
    feature = "mysql",
    feature = "mssql",
    feature = "turso"
))]
pub trait Param: SqliteParam + PostgresParam + MysqlParam + MssqlParam + TursoParam {}

#[cfg(all(
    feature = "sqlite",
    feature = "postgres",
    feature = "mysql",
    feature = "mssql",
    feature = "turso"
))]
impl<T> Param for T
where
    for<'a> T: 'a
        + Send
        + Encode<'a, sqlx::Sqlite>
        + Type<sqlx::Sqlite>
        + Encode<'a, sqlx::Postgres>
        + Type<sqlx::Postgres>
        + Encode<'a, sqlx::MySql>
        + Type<sqlx::MySql>
        + MssqlParam
        + TursoParam,
    for<'a> &'a T: Send,
{
}
